# Generated by Django 5.1.3 on 2024-11-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_slip', models.FileField(upload_to='documents/result_slips/')),
                ('birth_certificate', models.FileField(upload_to='documents/birth_certificates/')),
                ('admission_letter', models.FileField(upload_to='documents/admission_letters/')),
            ],
        ),
    ]
