# Generated by Django 5.1.3 on 2024-11-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_admissiondocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissiondocument',
            name='preferred_path',
            field=models.CharField(blank=True, choices=[('STEM', 'STEM'), ('Arts and Sports Science', 'Arts and Sports Science'), ('Social Sciences', 'Social Sciences')], max_length=100, null=True),
        ),
    ]
